[ML] Avoid assignment timeouts in MlDistributedFailureIT (#70950)
This change should fix the problem of #68685 where
MlDistributedFailureIT.testJobRelocationIsMemoryAware
can fail with "expected:<4> but was:<0>" because
persistent task assignment for the small jobs that
need reassigning after the simulated failure is
not checked often enough.

It also adds even more test logging for the other
failure covered by #68685, "expected:<1> but was:<2>".