Fixing randomization issue for TextSimilarityRankRetrieverBuilderTests (#112594)
Closes https://github.com/elastic/elasticsearch/issues/112531.

Due to randomly generating a `TextSimilarityRankRetrieverBuilder`, it
could be the case that `rankWindowSize` < 10 (which is the default
`size` parameter) causing validation errors when parsing source and the
following exception

```
org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: [rank] requires [rank_window_size: 4] be greater than or equal to [size: 10]
```

In this PR we just increase the lower bound for the randomly created
retriever to be 100 to ensure that it is always greater than `size`.