Add java.net.NetPermission for apm's plugin security (#99474)
when apm is enabled it throws a security manager exception:
java.security.AccessControlException: access denied ("java.net.NetPermission" "getProxySelector")
This commit adds a permission so that apm can be enabled